### ISSUE TITLE
Initialise tags content to pg tabe

### ISSUE THREAD

**Issue by SimonLab** [SimonLab/tags-system#10]
From a json file add the tags in the table (if the table doesn't exists yet) when the plugin is registered

**Comment by JMurphyWeb** [comment]
How does the plugin know which file to use & what structure the data is in?

**Comment by mk4111** [comment]
@JMurphyWeb - I think we'd use the 'fs' core module to readFile and process the data

**Comment by SimonLab** [comment]
At the moment we can keep the structure simple and update it when we add more features:
```
[
  {
    name: 'the tag name'
    active: true
  },
...
] 
```

I think this json tags should be passed as an options to the plugin as we want the user to add or delete easily the tags

**Comment by JMurphyWeb** [comment]
Starting on this now.

I am going to assume our plugin is given a JSON stringified array in the above format and write a script to add that data to the 'tags' db.

**Comment by SimonLab** [comment]
I think you can pass a real array in the options, it doesn't have to be stringify

**Comment by JMurphyWeb** [comment]
ok thanks. I will work on the script first, then passing the data via options.

**Comment by JMurphyWeb** [comment]
Looking into using the postgress-node module

**Comment by JMurphyWeb** [comment]
After looking into this a little, i am putting 2hrs estimate.

**Comment by JMurphyWeb** [comment]
thanks

**Comment by JMurphyWeb** [comment]
@SimonLab will the name to double quoted? I think SQL treats single and double quotes differently

**Comment by JMurphyWeb** [comment]
```[
  { "name": "frank", "active": true },
  { "name": "flop", "active": true },
  { "name": "flip", "active": true }
]```

This is what I get from readFileSync. Need to amend my script to take account for the double quotes.

**Comment by JMurphyWeb** [comment]
Script is fine. All entries are being added to dB.

Moving onto testing.

Having a problem that the PG connection is not closing when tests are finished. @mk4111 @SimonLab any ideas on how we want to manage this?

**Comment by JMurphyWeb** [comment]
in server.js
```
var fs = require('fs');

var tagsData = JSON.parse(fs.readFileSync('./example/tags.json').toString());

server.register({
  register: tags,
  options: { tags: tagsData }
}
```

**Comment by JMurphyWeb** [comment]
Tests are hanging. I am working on this: https://github.com/SimonLab/tags-system/issues/4#issuecomment-258813645
