### ISSUE TITLE
Add precommit hook!

### ISSUE THREAD

**Issue by mk4111** [SimonLab/tags-system#15]
Add pre-commit hook to ensure 100% coverage, tests are passing and that linting-standards are met.

**Comment by JMurphyWeb** [comment]
this is being done as a part of #3 
It does not cover pre commit hook for tests but it will be easy to add once the pre commit stuff is merged in

**Comment by mk4111** [comment]
I'll keep this open just for the tests then maybe?

**Comment by JMurphyWeb** [comment]
Add coverage check to the test script, or maybe it is nicer to add a coverage script which checks coverage.

**Comment by SimonLab** [comment]
resolved with #16 16
