### ISSUE TITLE
Change function name to request.tags

### ISSUE THREAD

**Issue by JMurphyWeb** [SimonLab/tags-system#24]
I want to change the name that we expose via the request object to `tags`

Is that ok @mk4111 @SimonLab ?

**Comment by SimonLab** [comment]
Unfortunately for you I think that we need to change the ```jackmisawesome``` function :wink:

**Comment by mk4111** [comment]
Sad times! Jack is still awesome though!!! <3

**Comment by JMurphyWeb** [comment]
closing this issue as i was a little confused of my task when i made it.
