### ISSUE TITLE
Closing the client

### ISSUE THREAD

**Issue by JMurphyWeb** [SimonLab/tags-system#25]
Currently I am creating a connection in our plugin: 
```
var pg = require('pg');
var client = new pg.Client();

// connect the client
client.connect(function (err) {
  Hoek.assert(!err, err);
});
```

However the tests hang as there is no way to close the client.
I tried to expose a closing function in the plugin:
```
  server.app.closeClient = function () {
    // disconnect the client
    client.end(function (err) {
      Hoek.assert(!err, err);
    });
  };
```

And run the function in the test file:
```
tape('teardown', function (t) {
  server.app.closeClient();
  t.end();
});
```

However it gives me the following failure:
<img width="855" alt="screen shot 2016-11-07 at 11 42 50" src="https://cloud.githubusercontent.com/assets/12638261/20056920/806f0516-a4e0-11e6-9e0b-b548d9be628e.png">

**Comment by JMurphyWeb** [comment]
No matter where I run that client.end function, it gives me the same error.

**Comment by JMurphyWeb** [comment]
I am happy to look into it a bit more. But would appreciate a quick look over @SimonLab in case you have seen this before?

**Comment by JMurphyWeb** [comment]
Going to pick my way through https://github.com/dwyl/hapi-postgres-connection/blob/master/test/_create_test_db.js for a solution

**Comment by JMurphyWeb** [comment]
I'm going to try going down the `pg.connection` route

**Comment by SimonLab** [comment]
I had this error with redis and the way I resolve this is by making sure to have a reference to my redis object that I can close (a bit like you've done with the closeClient function). I think I used https://github.com/dwyl/redis-connection to do this. I think it's a good idea to try to see how hapi-postres-connection is resolving this issue.

**Comment by JMurphyWeb** [comment]
That is exactly what I have tried to do. But it seems to be an error in the way of overall implementation. 

It seems that this pg.connect might be the way to go so am investigating that now.

**Comment by JMurphyWeb** [comment]
It seems like I will be re-writing the hapi-postgres-connection plugin if I am to implement this properly.

Do we need to create a client in the plugin?

**Comment by SimonLab** [comment]
Ok maybe it might be worth to try to just pass the client to the plugin as an option (see #4  ). Hopefully you will be able to run your tests and we can still try to search if there is another solution

**Comment by JMurphyWeb** [comment]
So should I add hapi-postgres-connection to our project?

**Comment by SimonLab** [comment]
I didn't have a proper look yet at hapi-postgres-connection but if it make the application easier to use with Postgres, yes we can try. Have you try to just use a simple client and to pass it to the plugin?

**Comment by JMurphyWeb** [comment]
I have not. But my problem is closing the client so the tests don't hang. I worry that if i create a client and pass it to the plugin, I will still have the same problem. I think hapi-postgres-connection does that work for us.

**Comment by JMurphyWeb** [comment]
Will attempt to implement hapi-postgres-connection into the app

**Comment by JMurphyWeb** [comment]
Annoyingly I am still having problems when using Hapi-postgres-connection.

The problem being, I cannot access the client that hpc creates in a plugin, because the hpc plugin hasn't had enough time to initialise itself yet. This is more or less the same issue I was having before with trying to attach a `done` function to server.app. By the time the tests were run, the function hadn't been added to server.app.

Possible solutions: 
 - Hapi module glue seems to be built for this purpose. I don't particularly like the idea of using glue as it means anyone who uses this module will also have to use glue..
 - We could expose a route that initialises our DB and can only ever be run once. Again not ideal.

I never knew that registering plugins could be such a pain.
