### ISSUE TITLE
add goodpart

### ISSUE THREAD

**Issue by SimonLab** [SimonLab/tags-system#3]
Add [goodparts](https://github.com/dwyl/goodparts) to keep consistency in the code with pre-commit hook

**Comment by JMurphyWeb** [comment]
I have added the pre-commit module and a the pre-commit script to the package.json. 

When committing, the linter runs its checks, but if there is an error, it does not stop the commit from happening.

@eliascodes @shouston3 @SimonLab sort it out.

**Comment by shouston3** [comment]
What if the linter passes, but the tests fail, does the pre-commit hook cause the commit to be aborted then?

Also, could you provide steps to replicate the issue

**Comment by eliascodes** [comment]
@JMurphyWeb I think this is because the goodparts CLI doesn't exit with code 1 if there are errors. Leave an issue in the goodparts repo and I will fix today.

**Comment by JMurphyWeb** [comment]
@eliascodes I was thinking it was something like this. I will make an issue if i remember.

**Comment by eliascodes** [comment]
@JMurphyWeb I've already written the fix. It's waiting on a branch for your issue!

**Comment by SimonLab** [comment]
Thanks for the investigation @eliascodes :+1: . I've just created an [issue](https://github.com/dwyl/goodparts/issues/266) on Goodparts

**Comment by JMurphyWeb** [comment]
Done @eliascodes ❤️
