### ISSUE TITLE
Treating async plugin registration as though it is sync

### ISSUE THREAD

**Issue by JMurphyWeb** [SimonLab/tags-system#30]
Tests being run before plugin has registered.

Solution: Putting the initialisation of the server in a function and exposing the server via a callback should fix our async plugins problem.

Example: https://github.com/SimonLab/simpleServer/blob/master/lib/index.js

**Comment by JMurphyWeb** [comment]
```

// set up server
tape('set up server', function (t) {
  init(2000, function (err, newServer) {
    if (err) {
      return t.fail();
    }
    server = newServer;

    return t.end();
  });
});

```

**Comment by JMurphyWeb** [comment]
Tests run fine.
When i try to run the server locally using start.js:
```
'use strict';

var Hoek = require('hoek');
var init = require('./server.js').init;


init(process.env.PORT || 3000, function (err, server) {
  Hoek.assert(!err, err);
  process.stdout.write('server listening on port ' + server.info.uri + '\n');
});
```

I get a log: `server listening on port http://Jacks-MBP:3000`
But when I visit that address, i get chrome's not found page

**Comment by JMurphyWeb** [comment]
I have been working on this for an hour now

**Comment by SimonLab** [comment]
You don't start your server, you need to do this before returning your callback, see https://github.com/SimonLab/tags-system/pull/29/files#r87177267

**Comment by JMurphyWeb** [comment]
Ohhh yeah! I should have taken a break! Thanks

**Comment by JMurphyWeb** [comment]
I think we have decided on the above init function.
