### ISSUE TITLE
Add test for new function of plugin

### ISSUE THREAD

**Issue by SimonLab** [SimonLab/tags-system#8]
Create a test which check that the [function](https://github.com/SimonLab/tags-system/blob/5ddb845798225a4522d91409f457afbd3034583e/index.js#L3) has been added to the request object of the server.

To Do:
- [x] Install tape and istanbul
- [x] Write a test to find the ```typeof``` request.jackmisawesome is a function.

**Comment by mk4111** [comment]
As agreed with @JMurphyWeb  and @SimonLab - going to work on this now :)

**Comment by mk4111** [comment]
Updating the main description to specify what I think we'll need to do to get this working quickly and easily.

**Comment by mk4111** [comment]
Just installed tape and istanbul, wondering if I should sort out codecov right now... (Will raise this as a separate issue)

**Comment by mk4111** [comment]
Returning a biiiiig response object. Going to copy it into atom, beautify the contents and find where jackmisawesome is!

**Comment by mk4111** [comment]
Found it! Have now changed the method to become a function, so that we can now do ```typeof``` on the method and get 'function' back! If method _does not_ exist, we get 'undefined' returned to us, so we can now check if (a) the method _exists_ in the first place, (b) the method is of a type function

**Comment by mk4111** [comment]
Wondering if we should add a pre-commit hook to this.

**Comment by mk4111** [comment]
ALSO - is there a better way to close the server connection? without server.stop, the tests hang. This was also an issue we had before, but is/was unresolved... I won't link it here, just so that we won't worry the clients with our enhancements!

**Comment by mk4111** [comment]
coverage isn't 100%! The contents of the mock function need to be tested!

**Comment by mk4111** [comment]
Done!

**Comment by mk4111** [comment]
Note to self:
Remember the _in progress_ label next time!
