### ISSUE TITLE
Create pg tables

### ISSUE THREAD

**Issue by SimonLab** [SimonLab/tags-system#9]
When the plugin is registered on the server it should create the tables if they don't exists yet

-------

Update:

Create a .sql file, containing commands that will
- [x] Create a new table called ```tags```, _if_ it doesn't exist already
- [x] Add dummy data to table see #10
- [x] Check to see if the row already exists in the table

**Comment by mk4111** [comment]
@SimonLab - I think dwyl have a great example [here](https://github.com/dwyl/hapi-login-example-postgres/blob/master/lib/database_setup.sql#L7) that we can use :)

**Comment by SimonLab** [comment]
yes I think it will look very similar

**Comment by mk4111** [comment]
Will be working on this issue this morning!

**Comment by mk4111** [comment]
So we will be creating a .sql file, containing commands that will
- [ ] Create a new table called ```tags```, _if_ it doesn't exist already
- [ ] Add dummy data to table
- [ ] Add a check to see if the row already exists in the table

**Comment by mk4111** [comment]
@SimonLab - I'm a little confused about what I need to achieve; Is the .sql file all I need to create to resolve this issue?
In order to write some tests (without the script), I need to do some postgres setup. Should this be a separate issue?
Or should I postpone tests until the two related issues are combined?

**Comment by mk4111** [comment]
Need to figure out how to pass arguments into .sql file

**Comment by mk4111** [comment]
Will first start by updating the readme.md

**Comment by SimonLab** [comment]
@mk4111 yes you just need to load a .sql file into your pg client which will create the table. It might be worth to check how @JMurphyWeb is trying to resolve the issue about the client not closing in the tests

**Comment by mk4111** [comment]
@SimonLab - Great! Thank you!

**Comment by mk4111** [comment]
@SimonLab - how and where are we planning on invoking the create table functionality and add all tags to db functionality? Together or separately? I think @JMurphyWeb has created a function to add tags so I'm a little confused about the flow....!

**Comment by SimonLab** [comment]
I think the first step is to create the table when the server start. Don't worry about adding content to the table yet (it's the role of the issue #10 ). I think the idea is to have a script that load and execute the sql which is going to create the table. This script should be executed each time the server start (we can see later if we need to change this behaviour). You can try this now without test, push it and create a WIP PR then you can join us to try to resolve the tests/pg client issue. Once this issue is resolve you will be able to add tests to the PR, hopefully it is a bit more clear, let me know.

**Comment by mk4111** [comment]
@SimonLab - that makes muuuch more sense! Thank you!!
